Created new method to sync dump. Method is called in a loop for each host (in a multi-host backup situation)

diff --git a/db-backup b/db-backup
--- a/db-backup
+++ b/db-backup
@@ -1,37 +1,70 @@
-#!/bin/bash
-#Version 0.2.2
-#db-backup
-#
-#####################################################################
-# Script does four things;
-# -Backs up a database to specified path
-# -Compress the backup using gzip compression tool
-# -Encrypt the backup
-# -rsync the backup directory to (a) file server(s).
-# 
-##################################################################
-# Created: Emmanuel Toko 2010-10-10 09:00 0.1
-# Modified: Emmanuel Toko 2011-05-04 20:06 0.11
-#####################################################################
 
 #Variables
 DATE=`date +%F~%T`
-FILENAME=/home/username/backups/backup-$DATE.sql
-LOGFILE=/home/username/backups/log/backup-log
-BACKUPDIR=/home/username/backups/
+FILENAME="$HOME" "backups/openmrs-$DATE.sql"
+LOGFILE="$HOME" "backups/log/backup-log"
+BACKUPDIR="$HOME" "/home/openmrs/backups/"
 MKDIR=/bin/mkdir
 TOUCH=/usr/bin/touch
+LOGGER=/usr/bin/logger
 
 if [ -e $BACKUPDIR ]
 then
-	
+	echo "Backup directory exists"
 else
 	$MKDIR -p $BACKUPDIR/log
 	$TOUCH $LOGFILE
 fi
 
+get_host() {
+
+HOSTS=("${@}")
+
+
+for RHOST in ${HOSTS[@]}
+do
+    HOST=`echo RHOST | cut -d':' -f 1 | cut -d'@' -f 2`
+    
+    count=$(ping -c $COUNT $HOST | grep 'received' | awk -F',' '{ print $2 }' | awk '{ print $1 }')
+    if [ $count -eq $SUCCESS_STATUS ]; then
+    # 100% failed
+        OFFLINE_HOSTS=$OFFLINE_HOSTS" "$RHOST
+        log_failure_msg "$RHOST is down ($?)"
+        #echo "Host : $RHOST is down (ping failed) at $(date)" #| mail -s "$SUBJECT" $EMAILID
+        #echo "Host : $RHOST is down (ping failed) at $(date)" &>>$LOGFILE
+        echo "Host : $RHOST is down (ping failed) at $(date)" | tee -a $LOGFILE
+    else
+        log_action_begin_msg "Copying backups to host: $RHOST"
+        $RSYNC -ar $BACKUPDIR $RHOST
+        if [ "$?" -eq "$SUCCESS_STATUS" ]
+        then
+            log_action_end_msg "$?"
+            echo "Successfully copied backups to host: $RHOST" | tee -a $LOGFILE
+        else
+            log_failure_msg "$?"
+            echo "Experienced an error when copying the backups to host: $RHOST" | tee -a $LOGFILE
+        fi
+        #echo "$RHOST is online"
+    fi
+done
+echo $1	$2
+}
+
+get_host $RHOST
+echo "$1"
+
+exit
+
 ##Space separated list of backup hosts Backup hosts
-RHOSTS="user1@192.168.56.1:backups user2@192.168.10.9:backups/ user3@172.16.1.11:backups user4@192.168.50.1:"
+RHOSTS=(
+	"chapati@192.168.126.11:backups/openmrs/" 
+	"openmrs@192.168.126.9:openmrs_home/openmrs_backup/" 
+	"posho@192.168.5.3:openmrs/backups/" 
+	"gears@192.168.5.1:openmrs/backups"
+)
+
+get_host
+exit 0
 
 #Programs
 MYSQLDUMP=/usr/bin/mysqldump
@@ -47,22 +80,24 @@ UNLINK=/usr/bin/unlink
 #LSB log-* functions
 . /lib/lsb/init-functions
 
-if [ -e $MYSQLDUMP ]
-then
-	echo "Fatal exception: mysqldump was not installed...."
-	log_failure_msg "mysqldump was not installed"
-	exit 1
-fi
+[ -x "$MYSQLDUMP" ] || exit 1
 
+log_failure_msg "mysqldump was not installed"
+exit 1
+
+if [ ! -x $GPG ]
+then
+	log_warning_msg "gpg is not installed backup won't be encrypted"
+fi
 echo "**********************************************************" &>> $LOGFILE
 
 echo
-echo "  Backup operations for date: $DATE" &>>$LOGFILE
+echo "openmrs Backup operations for date: $DATE" &>>$LOGFILE
 
-#Backup db
-echo "Backing up   database..." &>> $LOGFILE
-log_action_begin_msg "Backing up   database..."
-$MYSQLDUMP -u username -pusername username > $FILENAME
+#Backup openmrs db
+echo "Backing up openmrs database..." &>> $LOGFILE
+log_action_begin_msg "Backing up openmrs database..."
+$MYSQLDUMP -u openmrs -p1nvene0 openmrs > $FILENAME
 
 SUCCESS_STATUS=0
 
@@ -76,8 +111,8 @@ else
 fi
 
 #Compress file
-echo "Compressing   db dump... $FILENAME" &>>$LOGFILE
-log_action_begin_msg "Compressing   backup using gzip..."
+echo "Compressing openmrs db dump... $FILENAME" &>>$LOGFILE
+log_action_begin_msg "Compressing openmrs backup using gzip..."
 $GZIP $FILENAME
 if [ "$?" -eq "$SUCCESS_STATUS" ]
 then
@@ -92,7 +127,7 @@ fi
 log_action_begin_msg "Encrypting backup"
 FILE_EXTENSION=".gz"
 COMPRESSED_FILENAME=$FILENAME$FILE_EXTENSION
-$GPG --yes --passphrase="y0urpa55phra53" -c $COMPRESSED_FILENAME
+$GPG --yes --passphrase="?mamaputaty!yes" -c $COMPRESSED_FILENAME
  	
 if [ "$?" -eq "$SUCCESS_STATUS" ]
 then
@@ -113,30 +148,34 @@ COUNT=5
 
 # email report when
 SUBJECT="Ping failed"
-EMAILID="username@localhost"
+EMAILID="openmrs@localhost"
+OFFLINE_HOSTS=""
 
-for RHOST in $RHOSTS
+
+sleep 120 #wait 2 minute(s) before we attempt to reconnect to the failed/offline hosts to see if they are back online
+
+log_action_begin_msg "Trying to copy (again) to failed hosts"
+
+for RHOST in $OFFLINE_HOSTS
 do
-    USER_AND_HOST=`echo $RHOST| cut -d':' -f 1`
-    HOST=`echo $USER_AND_HOST| cut -d'@' -f 2`
+    HOST=`echo $RHOST | cut -d':' -f 1 | cut -d'@' -f 2`
     
     count=$(ping -c $COUNT $HOST | grep 'received' | awk -F',' '{ print $2 }' | awk '{ print $1 }')
     if [ $count -eq $SUCCESS_STATUS ]; then
     # 100% failed
+        $OFFLINE_HOSTS=$OFFLINE_HOSTS+$RHOST
         log_failure_msg "$RHOST is down ($?)"
-        echo "Host : $RHOST is down (ping failed) at $(date)" #| mail -s "$SUBJECT" $EMAILID
-        echo "Host : $RHOST is down (ping failed) at $(date)" &>>$LOGFILE
+        echo "Host : $RHOST is down (ping failed) at $(date)" | tee -a $LOGFILE
     else
         log_action_begin_msg "Copying backups to host: $RHOST"
         $RSYNC -ar $BACKUPDIR $RHOST
         if [ "$?" -eq "$SUCCESS_STATUS" ]
         then
             log_action_end_msg "$?"
-            echo "Successfully copied backups to host: $RHOST"
-            echo "Successfully copied backups to host: $RHOST" &>>$LOGFILE
+            echo "Successfully copied backups to host: $RHOST" | tee -a $LOGFILE
         else
             log_failure_msg "$?"
-            echo "Experienced an error when copying the backups to host: $RHOST" &>>$LOGFILE
+            echo "Experienced an error when copying the backups to host: $RHOST" | tee -a $LOGFILE
         fi
         #echo "$RHOST is online"
     fi
